spring:
  application:
    name: Myoppingmall

  datasource:
    url: jdbc:postgresql://localhost:5432/myoppingmall
    username: postgres
    password: 3930
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  jwt:
    secret: "wgfaqwe_12qsjdkho20_98sd31t4yf4q"
    access-token-exp-seconds: 1800
    refresh-token-exp-second: 1209600


springdoc:
  swagger-ui:
    path: /swagger
  api-docs:
    path: /api-docs